# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2481a2ea0924216400589b756ae6a202c62cb9599960fa57fa5c222c371a3cd43411636af8e27055874f9666016dd3cc9d7d2fdc250cab3e52b0e09979ceff2d

test:
  secret_key_base: 4e7db73898a6fc0753aaebb7e9d3c2005ba87b44bab68de1f1d8437a9b6cb549780b7b9071792ff710f397ab40116a4e61cbdc18da1f896d75bf125b4c175331

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
